### PR TITLE
Add an inside observer and a property as an updates indicator

### PR DESCRIPTION
**Pull request by lancedikson**
Seems like some people run into the same question: #216 and #88. I've found a good and flexible solution to define observer inside of Route or Controller. But here is a proposal for a default one way to track updates. I'm not sure that it's the best way to do it, so let's discuss if something isn't perfect :)

### CODE REVIEW

**Comment by broerse** [comment]
@lancedikson @mharris717 what do you think?

**Comment by lancedikson** [comment]
@mharris717, one more ping :)

**Comment by broerse** [comment]
@chrisccerami I think I can merge this but can you take a look?

**Comment by broerse** [comment]
@lancedikson Just published 3.0.2. Thanks!

**Pull request merged**
