### PR TITLE
Fix ember-component.send-action deprecation introduced in ember 3.4

### PR DESCRIPTION
**Pull request by rinoldsimon**

### CODE REVIEW

**Comment by broerse** [comment]
@mixonic It seems yarn is not working with Travis see https://github.com/mharris717/ember-cli-pagination/pull/230#issuecomment-337302955 Do you know how to fix this?

**Comment by rinoldsimon** [comment]
Updating nodejs will resolve the issue. But even we have to look at minimum supported node version will even change

**Comment by rinoldsimon** [comment]
https://github.com/yarnpkg/yarn/issues/6900

**Comment by bimalm** [comment]
```
npm uninstall -g yarn 
npm install -g yarn@1.12.3  
```
worked for me at Ubuntu 16.04

**Pull request closed without merging**
