### PR TITLE
Cleaning out ArrayController

### PR DESCRIPTION
**Pull request by acorncom**

### CODE REVIEW

**Comment by acorncom** [comment]
@mharris717 I think this build failed because of the jQuery pinning problem.  Let me know when you've got that pushed up and I can rebase here if you want me to

**Comment by jsangilve** [comment]
@acorncom considering issue #146, I think this PR shouldn't be merged. Using Binding for queryParams is broken on Ember 2.X.X

**Comment by broerse** [comment]
@jsangilve this works:
https://github.com/mharris717/ember-cli-pagination/blob/master/tests/dummy/app/controllers/todos/local.js

I think we should change the docs. The queryParams Binding works with ember-cli 2.3.0-beta.1 https://github.com/mharris717/ember-cli-pagination/pull/166

@jsangilve What is the Binding issue? All tests for ember-cli 2.3.0-beta.1 pass.

**Comment by jsangilve** [comment]
@broerse Sorry for my late reply. QueryParams Binding seems to work in terms of requesting new pages, but the URL is not updated when the page changes (when you click `page-numbers` component). As detailed on issue #146, you get a `delegate is not a funcion` error.  

I'm doing remote pagination, so I actually tried binding as explained in the docs:

```javascript
export default Ember.Controller.extend({
  queryParams: ['page', 'perPage'],

  pageBinding: 'model.page',
  perPageBinding: 'model.perPage',
  totalPagesBinding: 'model.totalPages',

  page: 1,
  perPage: 5,

```
This is Ember 2.3.0.

At #146 comments, somebody fixed it doing this:
```javascript
export default Ember.Controller.extend({
  queryParams: ['page', 'perPage'],

  totalPagesBinding: 'model.totalPages',
  page: 1,
  perPage: 5,

  actions: {
    pageClicked(page) {
      this.set('page', page);
    },
}
```
This updates the URL properly. So, yes, maybe docs for remote pagination are wrong or there are some cases not covered by tests.

**Comment by broerse** [comment]
@acorncom Thanks! Just removed ArrayController from the docs without seeing this.

**Pull request closed without merging**
