### PR TITLE
Get route store correctly.

### PR DESCRIPTION
**Pull request by fidlip**
Using this.get('store') instead of this.store is better practice and it allow to use computed store etc.

### CODE REVIEW

**Comment by fidlip** [comment]
Hi, is there any problem with this?

**Comment by broerse** [comment]
Seems good to me. Can merge it now but we still need to fix https://github.com/mharris717/ember-cli-pagination/issues/186

**Comment by broerse** [comment]
Just Merged. Thanks! Hope to merge https://github.com/mharris717/ember-cli-pagination/pull/199 soon and release them together.

**Comment by broerse** [comment]
Released it in Beta. https://github.com/mharris717/ember-cli-pagination/releases/tag/v3.0.0-beta.1 Thanks!

**Pull request merged**
