### PR TITLE
support for ember-cli 2 series 

### PR DESCRIPTION
**Pull request by jcope2013**
to fix changes broken by upstream ember-cli-version-checker changing semver check

### CODE REVIEW

**Comment by jcope2013** [comment]
tests passing locally...

**Comment by mharris717** [comment]
Can you explain your intent? It looks like you removed the workaround that made it work, and then it failed as expected.

**Comment by jcope2013** [comment]
ember-cli-version-checker to use semver.gt which makes my fix no longer needed and is also broken with latest changes

https://github.com/rwjblue/ember-cli-version-checker/commit/b73d2989b09f86d28c5ba8fdbd19d5b49b589a56

https://github.com/rwjblue/ember-cli-version-checker/commit/2cf58ec6db36ebaa44e970f35c1eea454a0daf39

**Comment by broerse** [comment]
@jcope2013 does this mean we can rollback your PR and update to ember-cli-version-checker 1.1.5 ?

**Comment by jcope2013** [comment]
@broerse yeah

**Comment by broerse** [comment]
@mharris717 Do you want a PR for this or do you fix this on the branch where you have the double click cherry pick on?

**Comment by mharris717** [comment]
@broerse I cherry picked your click fix, bumped the version and released it, but didn't push to master yesterday. Just did the push.

**Comment by mharris717** [comment]
Look good? #161

**Comment by acorncom** [comment]
Looks like this can be closed, now that #161 has been merged

**Pull request closed without merging**
