### PR TITLE
Add dots...

### PR DESCRIPTION
**Pull request by broerse**
To see this enable showFL. It seems that if you want to disable the hover you have to change the stylesheet. Or is there some other way? I still need to write some tests.

### CODE REVIEW

**Comment by broerse** [comment]
What is the dots... status?

**Comment by mharris717** [comment]
Status is I probably should have merged it already. I'll refresh my memory shortly and get it done. Sorry for the delay.

**Comment by broerse** [comment]
No problem !

**Comment by mharris717** [comment]
Tests 84fd28fc65462f0a4e2835af7d76cd6369601f32

**Pull request merged**
