### PR TITLE
Move to new each syntax

### LINKED ISSUE #112: DEPRECATION: Using the '{{#each item in model}}' in Ember 1.13
DEPRECATION: Using the '{{#each item in model}}' form of the {{#each}} helper ('
myapp/templates/components/page-numbers.hbs' @ L13:C4) is deprecated. Please use
 the block param form instead ('{{#each model as |item|}}'). See http://emberjs.com/guides/deprecations/#toc_code-in-code-syntax-for-code-each-code for more details.

### PR DESCRIPTION
**Pull request by halfdan**
fixes #112

### CODE REVIEW

**Comment by benkonrath** [comment]
This looks fine to me. The tests seem to be run against really old version of ember-cli which might be cause the problems.

**Comment by miguelcobain** [comment]
:+1:

**Comment by halfdan** [comment]
Could we get this merged?

**Comment by broerse** [comment]
@halfdan I hope to Help Mike with https://github.com/broerse/ember-cli-pagination/tree/upgrade_027

Only one test failing on 1.13.8 on remote sorting. If it is fixed Mike can Pull it. We also need some checks and docs.

**Comment by broerse** [comment]
@halfdan It is now in the new 0.9.0 Thanks !!

**Comment by broerse** [comment]
@benkonrath Do you give a talk about this on the next Amsterdam Ember Meetup ;-)

**Comment by mharris717** [comment]
@halfdan thanks for taking the time to submit this PR. Apologies for how long it took, but glad it's finally in.

Have a great day.

**Pull request closed without merging**
