### PR TITLE
Changing store.find to store.query 

### PR DESCRIPTION
**Pull request by marcinsklodowski**
Since Ember 2.0 no longer supports store.find().

### CODE REVIEW

**Comment by broerse** [comment]
Thanks! We are working on https://github.com/broerse/ember-cli-pagination/tree/upgrade_027 Only the remote sorting test fails.

**Comment by gte451f** [comment]
@broerse So for those following this project with giddy anticipation, is this where active development is taking place?

https://github.com/broerse/ember-cli-pagination/tree/upgrade_027

In other words, if I want to test out the next version of the pager, is that were I should pull from?

**Comment by broerse** [comment]
@gte451f  No Mike is is working on the last failing test and will merge my branch in some form. My branch should work but in a few days I think Mike can release a 1.0.0. version for ember-cli > 1.13.0

**Comment by broerse** [comment]
@gte451f You can use https://github.com/mharris717/ember-cli-pagination/commits/upgrade_027_attempt unit it is pushed as 1.0.0.beta1

**Comment by marcinsklodowski** [comment]
Great, thanks for info, @broerse .

**Pull request closed without merging**
