### PR TITLE
Fix Ember 2.0 no longer supporting dependent keys ending in "@each"

### PR DESCRIPTION
**Pull request by mcm-ham**

### CODE REVIEW

**Comment by broerse** [comment]
Reading [this](http://guides.emberjs.com/v2.0.0/object-model/computed-properties-and-aggregate-data/)
> Note here that we use the special key [] instead of @each.foo (which is used for observing a specific dependent key, such as foo, on each item). This instructs Ember.js to only care about the array itself changing (such as adding/removing items), rather than changes to the items themselves.

I am not sure .[] is the same as .@each Can you point me to some docs?

**Comment by mcm-ham** [comment]
The `@each` syntax also monitors for changes to array just like `[]`; from docs for `todos.@each.isDone`:

```
1. The isDone property of any of the objects in the todos array changes.
2. An item is added to the todos array.
3. An item is removed from the todos array.
4. The todos property of the controller is changed to a different array.
```

Indeed the docs as far as I'm aware has always encouraged `todos.[]` usage over `todos.@each` but the latter still worked until https://github.com/emberjs/ember.js/pull/11990 hence it now doesn't work in Ember 2.0 (the intended usage for `@each` of `todos.@each.isDone` still works).

**Comment by broerse** [comment]
Thanks. I was not sure 1. was handled by .[]

I will add it to https://github.com/broerse/ember-cli-pagination/tree/upgrade_027 . Only 18 tests failing now. If you have time please take a look.

**Comment by mcm-ham** [comment]
> Thanks. I was not sure 1. was handled by .[]

You are right only 2-4 is handled by '[]'; just that in our case we've not specified a property on the objects in the array to observe for changes i.e. we have `content.@each` not `content.@each.someProperty`.

> I will add it to https://github.com/broerse/ember-cli-pagination/tree/upgrade_027 . Only 18 tests failing now. If you have time please take a look.

Thanks. I don't think I do have that time sorry, but if I do I will have a look.

**Comment by broerse** [comment]
@mcm-ham This is now in the new 0.9.0 Thanks!

**Comment by mharris717** [comment]
@mcm-ham thanks for taking the time to make this PR!

Closing, as your commit is in 0.9.0.

**Comment by mharris717** [comment]
And thanks for teaching me something, I didn't know that about [] vs each.

**Pull request closed without merging**
