### PR TITLE
Adds a hasPages alias so you can hide the pagination helpers

### PR DESCRIPTION
**Pull request by tonycoco**
Fixes https://github.com/mharris717/ember-cli-pagination/pull/32 with tests and a more fitting name.

### CODE REVIEW

**Comment by mharris717** [comment]
Thanks again!

Does it make sense to hide the component by default if there are no pages, or maybe to render a default template that says "No Pages" and can be easily overridden? Would love opinions.

**Comment by tonycoco** [comment]
I was thinking that, @mharris717 but then again, maybe we can just not that part of the API in the docs so people can utilize it.

**Comment by mharris717** [comment]
Normally I'd agree. Only problem here is that `hasPages` is on the page-numbers component, so you can't use it to hide itself in the user's template.

**Comment by mharris717** [comment]
Maybe we could add the same things on the PagedArrays and people could use those.

**Comment by tonycoco** [comment]
Oh, I misunderstood you. I was just thinking this is a feature for those of us that override the default component template.

**Comment by mharris717** [comment]
That's a good point. 

Going to accept it. I might add that additional stuff as well, but no need to hold this up. Will push out a new version soon. If pushing out a new version right away would help you out, let me know. 

Thanks a lot!

**Comment by tonycoco** [comment]
Just noticed this is goofed. It should be > 1 totalPages not 0. Sorry, I'll PR quickly.

**Comment by mharris717** [comment]
Hrm. I might be crazy, but I thought that was correct. I guess it's open to interpretation whether 1 page constitutes "having pages."

**Comment by tonycoco** [comment]
That doesn't work. Since, totalPages will always return 1. Never 0.

**Comment by mharris717** [comment]
Excellent point

**Comment by tonycoco** [comment]
#82 Fixes this

**Pull request merged**
