### PR TITLE
Bump ember-cli, ember-cli-babel

### PR DESCRIPTION
**Pull request by mixonic**
* Bump Ember CLI
* Bump Ember CLI Babel to 6.8.2, which will allow consumers to drop the shims file. This is a breaking change that drops support for Node < 4.
* Update general files per `ember init`, should make future upgrade simpler.
* Clean up some testing items, including re-locating the acceptance tests to the `acceptance` folder and out of the `integration` folder. Also fixing linting issues to get the suite passing with `eslint` 👍 
* Add versions of Ember to ember-try
* Use headless chrome for CI
* Upgrade Ember and Ember Data.
* Use `yarn`!

### CODE REVIEW

**Comment by mixonic** [comment]
This passes! I would love to see it in a release before Ember 2.17 😁

**Comment by broerse** [comment]
@mixonic Thanks for all this work! Not sure about `yarn` but merged anyway as [3.1.1](https://github.com/mharris717/ember-cli-pagination/releases/tag/v3.1.1)

**Comment by broerse** [comment]
@mixonic Released just in time 😁

**Comment by mixonic** [comment]
@broerse you will love yarn. Feel free to drop into the community slack if you have questions about it, `#-ember-cli` specifically has quite knowledgable people.

**Pull request merged**
