### PR TITLE
Move page-numbers component to addon's folder

### PR DESCRIPTION
**Pull request by lancedikson**
Related to #204. Now it's possible to extend the `page-numbers` component from an app.

### CODE REVIEW

**Comment by lancedikson** [comment]
Hey, @broerse. We really need to have it on production. I'm not sure about compatibility with previous versions of Ember-CLI, but for me going on 2.10.0 it works fine. Do you think it could be published soon?

**Comment by broerse** [comment]
@lancedikson do we need to add the `ember-cli-htmlbars` dependency for this?

**Comment by lancedikson** [comment]
@broerse, yes, definitely. Ember-CLI says that.

**Comment by broerse** [comment]
@lancedikson trust you on this ;-) Merged now.

**Comment by lancedikson** [comment]
@broerse, great, thank you! 👍  Would be nice to have a release with this feature :)

**Comment by broerse** [comment]
Perhaps I can find time tomorrow but would like to fix this also. https://github.com/mharris717/ember-cli-pagination/issues/186#issuecomment-271073725

**Pull request merged**
