### PR TITLE
Respect thenable semantics

### PR DESCRIPTION
**Pull request by asermax**
Hi there! 
I was trying to chain some promises while using a infinite paged array and bumped into a problem and was unable to do so. When checking the code I realized the `then` methods on the different paged arrays don't respect the usual `thenable` semantics, where the method should return a promise as well.
I modified the different paged arrays so they return an actual promise in every case, making the chaining posible.

Let me know if this change is acceptable for you and if I should add some test in any case.
Kudos for this great library!

### CODE REVIEW

**Comment by mharris717** [comment]
That's awesome! Those missing returns are the sign of a ruby programmer :)

Thanks a lot

**Comment by typeoneerror** [comment]
@broerse Can this be merged into the 3.x beta? I think this would also close my issue as well (https://github.com/mharris717/ember-cli-pagination/pull/173)

**Comment by broerse** [comment]
@typeoneerror Good point! Will merge now but I do not have time to release in the next 2 days.

**Comment by typeoneerror** [comment]
@broerse no rush! just seeing some good stuff in the PRs :) I'm going to be upgrading to the 3 beta in the next week here, so hopefully I'll have some time to start helping out here again. good luck!

**Comment by broerse** [comment]
@asermax @typeoneerror Just released [v3.0.0-beta.3](https://github.com/mharris717/ember-cli-pagination/tree/v3.0.0-beta.3) with this PR. Thanks!

**Pull request merged**
